### ISSUE TITLE
Symbol docs in API reference missing “Symbolic Values” info

### ISSUE THREAD

**Issue by jrobichaux** [HCL-TECH-SOFTWARE/domino-c-api-docs#1]
All of the docs in the API reference that are for multiple symbols (for example https://opensource.hcltechsw.com/domino-c-api-docs/reference/Symb/ACL_FLAG_xxx ) are missing the “Symbolic Values” information from the API Reference database

**Comment by raghu-madat** [comment]
We have fixed this issue. Now you should be able to see the Symbolic values.
