### ISSUE TITLE
OSLock: HANDLE or DHANDLE?

### ISSUE THREAD

**Issue by jrobichaux** [HCL-TECH-SOFTWARE/domino-c-api-docs#39]
Not a pull request because I'd like someone on the API team to check this first, but I think the [documentation for OSLock](https://github.com/HCL-TECH-SOFTWARE/domino-c-api-docs/blob/main/docs/reference/Func/OSLock.md) should state that the hObject parameter is a DHANDLE not a HANDLE.

**Comment by jrobichaux** [comment]
for reference, in osmem.h : 

```
void far * LNPUBLIC OSLockObject (DHANDLE Handle);
#define OSLock(blocktype,handle) ((blocktype far *) OSLockObject(handle))
#define OSUnlock(handle) OSUnlockObject(handle)
```

**Comment by Daniel-Nashed** [comment]
Yes I would agree. All HANDLES that Notes/Domino uses are DHANDLE in contrast to Windows HANDLE.
The header file is always the best reference here.
Header files are an extract from the original Notes/Domino source code.

**Comment by thampel** [comment]
Documentation was updated to reflect actuals.
